tasks:
  - name: httpie
    init : >
      sudo apt-get update && sudo apt-get upgrade -y 
    command: >
      pip install httpie &&
      gp sync-done init-httpie

  - name: siege
    command: >
      gp sync-await init-httpie &&
      sudo apt-get install siege &&
      siege -V &&
      gp sync-done init-siege
    
  - name: kafka-docker
    command: > 
      cd kafka-docker &&
      docker-compose up -d

  - name: kafka-zookeeper
    init : >
      gp sync-await init-siege &&
      sudo apt-get install openjdk-11-jdk -y  
    command: > 
      cd /usr/local &&
      sudo wget https://archive.apache.org/dist/kafka/2.5.0/kafka_2.12-2.5.0.tgz &&
      sudo tar xvf kafka_2.12-2.5.0.tgz &&
      sudo mv kafka_2.12-2.5.0 /usr/local/kafka &&
      gp sync-done init-zookeeper &&
      sudo /usr/local/kafka/bin/zookeeper-server-start.sh /usr/local/kafka/config/zookeeper.properties
      

  - name: kafka-server 
    init : gp sync-await init-zookeeper
    command: > 
      sudo /usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties &&
      gp sync-done init-kafka-server
  
  # curl -LO https://dl.k8s.io/release/v1.21.0/bin/linux/amd64/kubectl -o /workspace/kubectl
  # -LO 옵션 수행시 현재 경로에도 다운받고, 아웃풋 디렉토리에도 다운받는다
  # -L옵션을 안주면 다운을 1번하는데 -L옵션을 줘야 다운을 2번한다 
  # 서버에서 HTTP 301 이나 HTTP 302 응답이 왔을 경우 redirection URL 로 따라가서 다운로드 하기 떄문인듯!

  - name: kubectl
    command: >
      curl -L https://dl.k8s.io/release/v1.26.0/bin/linux/amd64/kubectl -o /workspace/kubectl &&
      sudo install -o root -g root -m 0755 /workspace/kubectl /usr/local/bin/kubectl &&
      kubectl version --client
      
  - name: python
    init: gp sync-await init-kafka-server
    command: >
      sudo apt install python-is-python3 &&
      python --versions
      
  - name: awscli
    command: >
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /workspace/awscliv2.zip &&
      unzip -o /workspace/awscliv2 /workspace &&
      sudo /workspace/aws/install
    
  - name: eksctl
    command: >
      curl --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp &&
      sudo mv /tmp/eksctl /usr/local/bin &&
      eksctl version 
      
  # - name: boot
  #   command: >
  #     cat ./config/init

  # - name: helm
  #   command: >
  #     curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 &&
  #     chmod 700 get_helm.sh &&
  #     ./get_helm.sh